fix: add missing dev dependencies after backstage update
> backstage-cli package build

Error: Cannot find module '@module-federation/enhanced/rspack'
Require stack:
- /Users/pravindahal/coop/backstage-k8s-scaffolder-actions/node_modules/.pnpm/@backstage+cli@0.35.4_d8cb632a0354fe1b4edff358122a768e/node_modules/@backstage/cli/dist/modules/build/lib/bundler/config.cjs.js
- /Users/pravindahal/coop/backstage-k8s-scaffolder-actions/node_modules/.pnpm/@backstage+cli@0.35.4_d8cb632a0354fe1b4edff358122a768e/node_modules/@backstage/cli/dist/modules/build/lib/bundler/bundle.cjs.js
- /Users/pravindahal/coop/backstage-k8s-scaffolder-actions/node_modules/.pnpm/@backstage+cli@0.35.4_d8cb632a0354fe1b4edff358122a768e/node_modules/@backstage/cli/dist/modules/build/lib/buildFrontend.cjs.js
- /Users/pravindahal/coop/backstage-k8s-scaffolder-actions/node_modules/.pnpm/@backstage+cli@0.35.4_d8cb632a0354fe1b4edff358122a768e/node_modules/@backstage/cli/dist/modules/build/commands/package/build/command.cjs.js
- /Users/pravindahal/coop/backstage-k8s-scaffolder-actions/node_modules/.pnpm/@backstage+cli@0.35.4_d8cb632a0354fe1b4edff358122a768e/node_modules/@backstage/cli/dist/modules/build/commands/package/build/index.cjs.js

 ELIFECYCLE  Command failed with exit code 1.